auth_enabled: false

limits_config:
  ingestion_rate_strategy: global
  ingestion_rate_mb: 20 
  ingestion_burst_size_mb: 30
  max_label_names_per_series: 100
  per_stream_rate_limit: 100MB
  per_stream_rate_limit_burst: 150MB
  max_query_series: 5000

server:
  http_listen_port: 3100
  http_server_read_timeout: 600s
  http_server_write_timeout: 600s
  grpc_listen_port: 3101
  grpc_server_max_recv_msg_size: 100000000
  grpc_server_max_send_msg_size: 150000000
  log_format: json
  log_level: debug

schema_config:
  configs:
    - from: 2023-08-08
      object_store: s3
      schema: v12
      store: tsdb
      index:
        period: 24h
        prefix: index_

storage_config:
  tsdb_shipper:
    active_index_directory: /loki/tsdb-index
    cache_location: /loki/tsdb-cache
    shared_store: s3
  aws:
    s3: http://loki:q7XMDpds9CJvjfWY@minio.:9000/loki
    s3forcepathstyle: true
    region: darlinghurst

common:
  path_prefix: /loki
  ring:
    kvstore:
      store: inmemory
  replication_factor: 1

tracing:
  enabled: true

querier:
  max_concurrent: 16
